### ISSUE TITLE
[FEATURE] Create `stackql-deploy init` starter project for `aws`

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-deploy#4]
**Feature Description**
Create starter template for `stackql-deploy` for the `aws` provider, including:

- A Virtual Private Cloud (VPC)
- Subnets (public and private)
- Internet Gateway
- Route Tables
- Security Groups
- EC2 Instance

**Example(s)**
Invoked using:

```bash
stackql-deploy init my-stack --provider aws
```

Example config:

```yaml
provider: aws
resources:
  vpc:
    cidr_block: 10.0.0.0/16
    enable_dns_support: true
    enable_dns_hostnames: true
  subnets:
    - name: public_subnet
      cidr_block: 10.0.1.0/24
      map_public_ip_on_launch: true
      tags:
        - key: Name
          value: Public Subnet
    - name: private_subnet
      cidr_block: 10.0.2.0/24
      tags:
        - key: Name
          value: Private Subnet
  internet_gateway:
    attach_to_vpc: true
  route_tables:
    - name: public_route_table
      routes:
        - destination_cidr_block: 0.0.0.0/0
          gateway_id: internet_gateway
      subnet_associations:
        - public_subnet
  security_groups:
    - name: web_sg
      description: Allow web traffic
      vpc_id: vpc
      ingress:
        - protocol: tcp
          from_port: 22
          to_port: 22
          cidr_blocks: 0.0.0.0/0
        - protocol: tcp
          from_port: 80
          to_port: 80
          cidr_blocks: 0.0.0.0/0
  instances:
    - name: web_server
      instance_type: t2.micro
      ami: ami-0c55b159cbfafe1f0 # Amazon Linux 2 AMI
      key_name: my-key-pair
      subnet_id: public_subnet
      security_group_ids:
        - web_sg
      tags:
        - key: Name
          value: Web Server
```
