### ISSUE TITLE
[FEATURE] All for generic `.iql` exports mapped to a named export

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-deploy#41]
**Feature Description**
If an `.iql` file is reused for more than one resource in a stack, how can we export a generic export as a named export.

**Example(s)**

`stackql_manifest.yml`: 
```yaml
...
  - name: transfer_user_systemx
    file: transfer_user.iql
    props:
      - name: transfer_user_username
        value: "{{ stack_env }}_systemx"
    exports:
      - transfer_user_systemx_username
      - transfer_user_systemx_arn
```
`transfer_user.iql`:

```sql
/*+ preflight */
SELECT COUNT(*) as count 
FROM aws.transfer.users 
where region = '{{ region }}' 
and data__ServerId = '{{ transfer_server_id }}' 
and data__UserName = '{{ transfer_user_username }}'

/*+ create */
INSERT INTO aws.transfer.users 
(
data__UserName,
data__ServerId,
data__HomeDirectoryType,
data__HomeDirectoryMappings,
data__Role,
data__Policy,
data__Tags,
region
)
SELECT
'{{ transfer_user_username }}',
'{{ transfer_server_id }}',
'LOGICAL',
'[{ "Entry": "/", "Target": "/{{ transfer_bucket_name }}/{{ transfer_user_username }}" }]',
'{{ transfer_access_role_arn }}',
string('{{ transfer_user_policy_data }}'),
'{{ global_tags | tojson }}',
'{{ region }}'

/*+ postdeploy, retries=5, retry_delay=5 */
SELECT COUNT(*) as count 
FROM aws.transfer.users 
where region = '{{ region }}' 
and data__ServerId = '{{ transfer_server_id }}' 
and data__UserName = '{{ transfer_user_username }}'

/*+ exports */
SELECT Arn as transfer_user_arn,
'{{ transfer_user_username }}' as transfer_user_username 
from aws.transfer.users 
where region = '{{ region }}' 
and data__ServerId = '{{ transfer_server_id }}' 
and data__UserName = '{{ transfer_user_username }}'
```
**Possible Approaches or Libraries to Consider**

`stackql_manifest.yml`: 
```yaml
...
  - name: transfer_user_systemx
    file: transfer_user.iql
    props:
      - name: transfer_user_username
        value: "{{ stack_env }}_systemx"
    exports:
      - transfer_user_username: transfer_user_systemx_username
      - transfer_user_arn: transfer_user_systemx_arn
```
allow `exports` to accept either a list of strings (as is) or a list of objects in the form of `exported_variable` (key) and `renamed_assigned_exported_variable` (value)
