### ISSUE TITLE
`stackql` and `stackql-deploy` version pinning

### ISSUE THREAD

**Issue by general-kroll-4-life** [stackql/stackql-deploy#44]
## Background

Currently `stackql-deploy` does not support version pinning for:

- `stackql`
- `stackql-deploy`

...however this feature is useful for determinism and maintenance.  Therefore this piece of work is simply to implement version pinning for these.

## Acceptance Criteria

- The `stackql` version can be supplied in the manifest file or command line, with command line overriding manifest file.
- The `stackql-deploy` version can be supplied in the manifest file or command line, with command line overriding manifest file.
- If supplied, then precisely the matching version (of either) will be downloaded and used, or an error will be thrown.
- If not supplied, then the latest available version will be used, per current behaviour.

### Implementation detail

This ticket does not specify implementation detail; it is up to the developer to decide and make a case for the preferred implementation. Probably the naive approach for the manifest file would be something like this:

```yaml
version: 1 # this is the version of the stackql-deploy grammar and unchanged from this ticket
name: my-stack-deployment
description: stackql-deploy IAC for my use case
stackql-version: v0.5.742 # new feature... the version shown is sitting on my laptop at the time of writing
stackql-deploy-version: 1.7.1 # new feature... the version shown is sitting on my laptop at the time of writing
```
