### ISSUE TITLE
[FEATURE]  Add support for auth variable scope override at resource level

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-deploy#47]
**Feature Description**
Provider auth uses the default environment variables for the given provider, we need the ability to override these at the resource level, exp for control plane-data plane context switching in the same stack.  This should be part of the `stackql_manifest.yml` file as provided in the example below:

```yaml
resources:
...
  - name: app_manager_api_key
    props:
      - name: display_name
        value: "{{ stack_name }}-{{ stack_env }}-app-manager-api-key"
      - name: description
        value: "Kafka API Key that is owned by 'app-manager' service account"
      - name: owner
        value:
         id: app_manager_id
         api_version: app_manager_api_version
         kind: app_manager_kind
    exports:
      - app_manager_api_key_id
      - app_manager_api_key_secret
  - name: users_topic
    # use context vars for custom auth
    auth:
      confluent:
        type: basic
        username_var: app_manager_api_key_id
        password_var: app_manager_api_key_secret 
    # set non exported env vars for the above, pass these along with the auth struct to the stackql commands
    props:
      - name: topic_name
        value: "users"
      - name: kafka_cluster
        value: {{ cluster_id }}
      - name: rest_endpoint
        value: {{ cluster_rest_endpoint }}
```
if the custom auth struct is provided to the stackql command, it is used along with command-specific environment variable assignment between the variable name values and their corresponding context values.
