### ISSUE TITLE
[FEATURE] Create `stackql-deploy init` starter project for `azure`

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-deploy#5]
### **Feature Description**
Create a starter template for `stackql-deploy` for the `azure` provider, including the following components:

- A Resource Group
- A Virtual Network
- A Subnet
- A Network Security Group
- A Public IP Address
- A Network Interface
- A Virtual Machine

### **Example(s)**
The starter template should be invoked using:

```bash
stackql-deploy init my-stack --provider azure
```
### **Example Template YAML**

```yaml
provider: azure
resources:
  resource_group:
    name: my-resource-group
    location: eastus
  virtual_network:
    name: my-vnet
    address_space: 10.0.0.0/16
    resource_group_name: my-resource-group
  subnet:
    name: my-subnet
    address_prefix: 10.0.1.0/24
    virtual_network_name: my-vnet
    resource_group_name: my-resource-group
  network_security_group:
    name: my-nsg
    resource_group_name: my-resource-group
    security_rules:
      - name: allow_ssh
        protocol: Tcp
        direction: Inbound
        access: Allow
        priority: 1000
        source_address_prefix: '*'
        source_port_range: '*'
        destination_address_prefix: '*'
        destination_port_range: 22
      - name: allow_http
        protocol: Tcp
        direction: Inbound
        access: Allow
        priority: 1001
        source_address_prefix: '*'
        source_port_range: '*'
        destination_address_prefix: '*'
        destination_port_range: 80
  public_ip:
    name: my-public-ip
    resource_group_name: my-resource-group
  network_interface:
    name: my-nic
    resource_group_name: my-resource-group
    ip_configurations:
      - name: ipconfig1
        subnet_name: my-subnet
        public_ip_name: my-public-ip
        network_security_group_name: my-nsg
  virtual_machine:
    name: my-vm
    resource_group_name: my-resource-group
    vm_size: Standard_B1s
    admin_username: azureuser
    admin_password: {{ PASSWORD }}
    network_interface_name: my-nic
    image_reference:
      publisher: Canonical
      offer: UbuntuServer
      sku: 18.04-LTS
      version: latest
```
