### ISSUE TITLE
[FEATURE] Create `stackql-deploy init` starter project for `google`

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-deploy#6]
Sure! Here’s a detailed GitHub issue for creating a `stackql-deploy` starter template for Google Cloud Platform (GCP), starting with a project and including additional components for a complete "Hello IaC" project.

---

### **Feature Description**
Create a starter template for `stackql-deploy` for the `gcp` provider, including the following components:

- A GCP Project
- A VPC Network
- A Subnet
- A Firewall Rule
- An External IP Address
- A Compute Instance

### **Example(s)**
The starter template should be invoked using:

```bash
stackql-deploy init my-stack --provider google
```
### **Example Template YAML**

```yaml
provider: google
resources:
  project:
    project_id: my-project
    name: My Project
  vpc_network:
    name: my-vpc
    auto_create_subnetworks: false
  subnet:
    name: my-subnet
    ip_cidr_range: 10.0.1.0/24
    region: us-central1
    network: my-vpc
  firewall_rule:
    name: allow-http-ssh
    network: my-vpc
    allowed:
      - protocol: tcp
        ports:
          - "22"
          - "80"
    source_ranges:
      - "0.0.0.0/0"
  external_ip_address:
    name: my-external-ip
  compute_instance:
    name: my-instance
    machine_type: e2-micro
    zone: us-central1-a
    subnetwork: my-subnet
    external_ip: my-external-ip
    image:
      family: debian-10
      project: debian-cloud
    boot_disk:
      initialize_params:
        size: 10
        type: pd-standard
```
